dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - stable
env:
  - CODECLIMATE_REPO_TOKEN=bbee33a0793c408f3034279fc9baa151056b58cc4784b4ba286b234e1df0d175
  - CODECLIMATE_API_HOST=https://codebeat.co/webhooks/code_coverage CODECLIMATE_REPO_TOKEN=75c0995f-d238-4d43-99a7-cc883bb0dd88
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - yarn config set registry "https://registry.npmjs.org"
  - yarn global add greenkeeper-lockfile@1
  - yarn global add codeclimate-test-reporter
before_script:
  - greenkeeper-lockfile-update
script:
  - node_modules/karma/bin/karma start karma.conf.js --single-run
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - codeclimate-test-reporter < coverage/lcov.info
